language: generic

sudo: required

services:
- docker

branches:
  only:
  - /^v.*$/

script:
- if [[ $TRAVIS_TAG = $TRAVIS_BRANCH ]]; then make push TAG=$TRAVIS_TAG; fi

notifications:
  email: false